=== Caberbar/1DAW-ML/2º Trimestre/almacen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DEFINICION DE ENTIDADES -->
<!ENTITY % direccion "(lugar, numero, cp, municipio)">
<!ENTITY % prefijo '(956|955|959|957|958|953|950|952) "956"'>
<!ENTITY % provincia '(Cádiz|Sevilla|Huelva|Córdoba|Granada|Jaén|Almería|Málaga) "Cádiz"'>
<!ENTITY % pais 'CDATA "España"'>
<!ENTITY % telefono "(fijo*, movil+)">
<!ENTITY % dia "(01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">
<!ENTITY % mes "(Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre)">
<!ENTITY % año "(2000|2001|2002|2003|2004|2005|2006|2007|2008|2009|2010|2011)">

<!-- DECLARACION ALMACEN -->
<!--DATOS: proveedor, producto, cliente, factura, pedido) -->

<!ELEMENT almacen (proveedor+, producto+, cliente+, factura*, pedido*)>

<!-- DECLARACION DE PROVEEDORES -->
<!--DATOS: idprov, nombreprov, direccionprov, tlfprov, faxprov) -->

<!ELEMENT proveedor (nombreprov+, direccionprov+, tlfprov+, faxprov+)>
<!-- La unica forma de garantizar que el idprov será unico para cada proveedor es ponerlo como atributo. Si lo pongo como elemento no puedo garantizar eso. -->
<!-- Además, hay que tener en cuenta que al ponerlo como atributo ID, despues se puede hacer referencia a él, mediante un atributo de tipo IDREF.-->
<!ATTLIST proveedor idprov ID #REQUIRED
                    pais CDATA #FIXED "España">
<!ELEMENT nombreprov (#PCDATA)>
<!ELEMENT direccionprov %direccion;>
<!ELEMENT lugar (calle|plaza|avenida)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT plaza (#PCDATA)>
<!ELEMENT avenida (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT municipio (#PCDATA)>
<!-- Los atributos de tipo lista de opciones, en los que se quiera establecer una opción por defecto, no pueden tener el tipo #REQUIRED. -->
<!ATTLIST direccionprov pais %pais;>
<!ATTLIST municipio provincia %provincia;>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT tlfprov %telefono;>
<!ELEMENT fijo EMPTY>
<!ATTLIST fijo prefijo %prefijo;
               numero CDATA #REQUIRED>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT faxprov (#PCDATA)>
<!ATTLIST faxprov prefijo %prefijo;
                  numero CDATA #REQUIRED >

<!-- DECLARACION DE PRODUCTOS -->
<!--DATOS: idprod, nombreprod, categoriaprod, pvpprod, idprov, stock) -->

<!ELEMENT producto (nombreprod, pvpprod, stockprod)>
<!ELEMENT nombreprod (#PCDATA)>
<!ATTLIST producto idprod ID #REQUIRED
                   idprov IDREF #REQUIRED
                   categoriaprod (Programas|Componentes|Pantallas|Impresoras|Teclados|Ratones|Multimedia) #IMPLIED>
<!ELEMENT pvpprod (#PCDATA)>
<!ELEMENT stockprod (#PCDATA)>

<!-- DECLARACION DE CLIENTES -->
<!--DATOS: idcli, nombrecli, direccioncli, tlfcli, faxcli) -->

<!ELEMENT cliente (nombrecli, direccioncli, tlfcli+, faxcli*)>
<!ATTLIST cliente idcli ID #REQUIRED>
<!ELEMENT nombrecli (#PCDATA)>
<!ELEMENT direccioncli %direccion;>
<!ATTLIST direccioncli pais %pais;>
<!ELEMENT tlfcli %telefono;>
<!ATTLIST faxcli prefijo %prefijo;
                  numero CDATA #REQUIRED >

<!-- DECLARACION DE FACTURAS -->
<!--DATOS: idfact, fechafact, lineafact(idprodfact, pu, total), idclifact, subtotalfact, ivafact, importefact) -->

<!ELEMENT factura (fechafact, lineafact+, subtotalfact, ivafact, importefact) >
<!ATTLIST factura idfact ID #REQUIRED 
                  idclifact IDREF #REQUIRED >
<!ELEMENT fechafact EMPTY >
<!ATTLIST fechafact dia %dia; #REQUIRED
                    mes %mes; #REQUIRED
                    año %año; #REQUIRED > 
<!ELEMENT lineafact EMPTY >
<!ATTLIST lineafact idprodfact IDREF #REQUIRED
                    cantidadfact CDATA #REQUIRED
                    pu CDATA #REQUIRED
                    total CDATA #REQUIRED >
<!ELEMENT subtotalfact (#PCDATA) >
<!ELEMENT ivafact (#PCDATA) >
<!ELEMENT importefact (#PCDATA) >

<!-- DECLARACION DE PEDIDOS -->
<!--DATOS: idped, fechaped, lineaped(idprodped), idcliped, fechaentregaped) -->

<!ELEMENT pedido (fechaenvioped, lineaped+, fechaentregaped) >
<!ATTLIST pedido idped ID #REQUIRED 
                 idcliped IDREF #REQUIRED >
<!ELEMENT fechaenvioped EMPTY >
<!ATTLIST fechaenvioped dia %dia; #REQUIRED
                    mes %mes; #REQUIRED
                    año %año; #REQUIRED > 
<!ELEMENT lineaped EMPTY >
<!ATTLIST lineaped idprodped IDREF #REQUIRED 
                   cantidadped CDATA #REQUIRED>
<!ELEMENT fechaentregaped EMPTY >
<!ATTLIST fechaentregaped dia %dia; #REQUIRED
                    mes %mes; #REQUIRED
                    año %año; #REQUIRED >

=== Caberbar/1DAW-ML/2º Trimestre/almacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./estiloalmacen.css" media="screen"?>
<!DOCTYPE almacen SYSTEM "./almacen.dtd">
<almacen>
    <proveedor idprov="CIF-11546987-G" pais="España">
        <nombreprov>URENDE</nombreprov>
        <direccionprov pais="España">
            <lugar>
                <avenida>San Javier</avenida>
            </lugar>
            <numero>34</numero>
            <cp>11251</cp>
            <municipio provincia="Cádiz">Jerez de la Frontera</municipio>
        </direccionprov>
        <tlfprov>
            <fijo prefijo="956" numero="136140"></fijo>
            <fijo prefijo="956" numero="136017"/>
            <movil>664554768</movil>
        </tlfprov>
        <faxprov prefijo="956" numero="136141"></faxprov>
    </proveedor>
    <proveedor idprov="CIF-21345543-K">
        <nombreprov>MEDIAMARKT</nombreprov>
        <direccionprov pais="España">
            <lugar>
                <plaza>De la Republica</plaza>
            </lugar>
            <numero>122</numero>
            <cp>20220</cp>
            <municipio provincia="Málaga">Malaga</municipio>
        </direccionprov>
        <tlfprov>
            <fijo prefijo="952" numero="100546"/>
            <movil>665773872</movil>
            <movil>665734342</movil>
        </tlfprov>
        <faxprov prefijo="952" numero="122133"></faxprov>
    </proveedor>
    
    <producto idprod="P1005" idprov="CIF-11546987-G" categoriaprod="Pantallas">
        <nombreprod>Monitor TFT 17" LG</nombreprod>
        <pvpprod>75.25€</pvpprod>
        <stockprod>25</stockprod>
    </producto>
    <producto idprod="P1010" idprov="CIF-21345543-K" categoriaprod="Impresoras">
        <nombreprod>Impresora Laserjet HP 5200</nombreprod>
        <pvpprod>115.70€</pvpprod>
        <stockprod>7</stockprod>
    </producto>
    <producto idprod="P2105" idprov="CIF-21345543-K" categoriaprod="Programas">
        <nombreprod>Panda Antivirus 2011</nombreprod>
        <pvpprod>32.15€</pvpprod>
        <stockprod>12</stockprod>
    </producto>
    <!--Tener en cuenta que los atributos de tipo ID tiene que ser nombres XML válidos, -->
    <!--por lo que no pueden empezar por numeros, por ello anteponemos la palabra dni. -->
    <cliente idcli="dni52297413-J">
        <nombrecli>Agustín Fernández Sánchez</nombrecli>
        <direccioncli pais="España">
            <lugar>
                <calle>Santo Tomás de Aquino</calle>
            </lugar>
            <numero>28</numero>
            <cp>41251</cp>
            <municipio provincia="Sevilla">Utrera</municipio>
        </direccioncli>
        <tlfcli>
            <movil>667554654</movil>
        </tlfcli>
    </cliente>
    <cliente idcli="dni520546676-H">
        <nombrecli>Ana Rodríguez Lara</nombrecli>
        <direccioncli pais="España">
            <lugar>
                <calle>Alfonso XIII</calle>
            </lugar>
            <numero>14</numero>
	    <cp>41200</cp>
            <municipio>Sevilla</municipio>
        </direccioncli>
        <tlfcli>
            <movil>665789876</movil>
        </tlfcli>
    </cliente>
    
    <factura idfact="F.1003" idclifact="dni52297413-J">
        <fechafact dia="22" mes="Mayo" año="2011"/>
        <lineafact idprodfact="P2105" cantidadfact="5" pu="32.15€" total="160.75€"/>
        <lineafact idprodfact="P1010" cantidadfact="1" pu="115.70€" total="115.70€"/>
        <subtotalfact>276.45€</subtotalfact>
        <ivafact>49.76€</ivafact>
        <importefact>326.21€</importefact>
    </factura>
    
    <pedido idped="PE1300" idcliped="dni520546676-H">
        <fechaenvioped dia="07" mes="Mayo" año="2011"/>
        <lineaped idprodped="P1005" cantidadped="7"/>
        <lineaped idprodped="P1010" cantidadped="2"/>
        <lineaped idprodped="P2105" cantidadped="23"/>
        <fechaentregaped dia="15" mes="Mayo" año="2011"/>
    </pedido>
</almacen>
