=== Caberbar/1DAW-ML/2º Trimestre/bdbiblioteca.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bdbiblioteca (socio+,libro)>

<!ELEMENT socio (nombre,direccion,tlf*,fechanac)>
<!ATTLIST socio dni ID #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (lugar,numero,bloque?,piso?,puerta?)>
<!ATTLIST direccion cp CDATA #REQUIRED>
<!ATTLIST direccion poblacion CDATA #REQUIRED>

<!ELEMENT lugar (Avda?,Plaza?)>
<!ELEMENT Avda (#PCDATA)>
<!ELEMENT Plaza (#PCDATA)>

<!ELEMENT numero (#PCDATA)>
<!ELEMENT bloque (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT puerta (#PCDATA)>

<!ELEMENT tlf (#PCDATA)>

<!ELEMENT fechanac EMPTY>
<!ATTLIST fechanac dia CDATA #REQUIRED>
<!ATTLIST fechanac mes CDATA #REQUIRED>
<!ATTLIST fechanac año CDATA #REQUIRED>



<!ELEMENT libro (titulo,autor,fechadq)>
<!ATTLIST libro isbn CDATA #REQUIRED>
<!ATTLIST libro tematica CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

<!ELEMENT fechadq EMPTY>
<!ATTLIST fechadq dia CDATA #REQUIRED>
<!ATTLIST fechadq mes CDATA #REQUIRED>
<!ATTLIST fechadq año CDATA #REQUIRED>

=== Caberbar/1DAW-ML/2º Trimestre/bdbiblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bdbiblioteca SYSTEM "./bdbiblioteca.dtd">

<bdbiblioteca>
  <socio dni="dni11.111.111-A">
         <nombre>Juan Orozco García</nombre>
         <direccion cp="11650" poblacion="">
                <lugar>
                         <Avda>San Jerónimo</Avda>
                 </lugar>
                 <numero>14</numero>
                 <bloque>3B</bloque>
                 <piso>2</piso>
                 <puerta>A</puerta>
         </direccion>
         <tlf>956136100</tlf>
         <tlf>656444888</tlf>
          <fechanac dia="6" mes="Diciembre" año="1980"/>
     </socio>
     <socio dni="dni22.222.222-B">
            <nombre>María Sánchez Figueroa</nombre>
            <direccion cp="11650" poblacion="Arcos de la Fra.">
                    <lugar>
                           <Plaza>Duque de Ahumada</Plaza>
                    </lugar>
                     <numero>46</numero>
            </direccion> 
            <fechanac dia="1" mes="Febrero" año="1974"/>
       </socio>
       <libro isbn="isbn84-415-1812-2" tematica="Ciencias">
                <titulo>XML Imprescindible</titulo>
                <autor>Rysty Harold</autor>
                 <fechadq dia="22" mes="Junio" año="2011"/>
       </libro>
</bdbiblioteca>
