=== Caberbar/1DAW-ML/2º Trimestre/liga.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DEFINICION DE ENTIDADES-->
<!ENTITY % categoriaFutbol "(Primera_Division|Segunda_Division|Tercera_Division)">
<!ENTITY % posicion "(Portero|Defensa|Delantero|Centro|Lateral)">
<!ENTITY % dia "(01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">
<!ENTITY % mes "(Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre)">
<!ENTITY % lugar "(Espa単ola|Extranjera)">
<!ENTITY % competicion "Espa単ola 2021/2022">
<!ENTITY % emision "(Abierto|Codificado)">

<!-- DECLARACION LIGA -->
<!--DATOS: juadores, entrenadores, arbitros, equipos, partidos, estadios, jornadas) -->
<!ELEMENT ligas (liga+)>

<!ELEMENT liga (jugadores+,entrenadores+,arbitros+,estadios+,equipos+,partidos+,jornadas+)>
<!ATTLIST liga temporada CDATA "2011/2012">
<!ATTLIST liga categoriaFutbol %categoriaFutbol; "Primera_Division" >

<!-- JUGADORES -->
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (nombre,apellidos+,fechanacimiento,alias+,nacionalidad,demarcacion)>
<!ATTLIST jugador id_jugador ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fechanacimiento EMPTY>
<!ATTLIST fechanacimiento dia %dia; #REQUIRED>
<!ATTLIST fechanacimiento mes %mes; #REQUIRED>
<!ATTLIST fechanacimiento ano CDATA #REQUIRED>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT nacionalidad EMPTY>
<!ATTLIST nacionalidad lugar %lugar; "Espa単ola">
<!ELEMENT demarcacion EMPTY>
<!ATTLIST demarcacion posicion %posicion; #REQUIRED>

<!-- ENTRENADORES -->
<!ELEMENT entrenadores (entrenador+)>
<!ELEMENT entrenador (nombre,apellidos+,fechanacimiento,alias+,nacionalidad,titulos)>
<!ATTLIST entrenador id_entrenador ID #REQUIRED>
<!ELEMENT titulos (#PCDATA)>

<!-- ARBITROS -->
<!ELEMENT arbitros (arbitro+)>
<!ELEMENT arbitro (nombre,apellidos+,alias+,nacionalidad)>
<!ATTLIST arbitro id_arbitro ID #REQUIRED>

<!-- ESTADIOS -->
<!ELEMENT estadios (estadio+)>
<!ELEMENT estadio (nombre, ubicacion, aforo)>
<!ATTLIST estadio id_estadio ID #REQUIRED>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT aforo (#PCDATA)>

<!-- EQUIPOS -->
<!ELEMENT equipos (equipo+)>
<!ELEMENT equipo (nombre, fechadeconstitucion, categoria,entrenador_equi,jugadores_equi+, estadio_equi)>
<!ATTLIST equipo id_equipo ID #REQUIRED>
<!ELEMENT fechadeconstitucion EMPTY>
<!ATTLIST fechadeconstitucion dia %dia; #REQUIRED>
<!ATTLIST fechadeconstitucion mes %mes; #REQUIRED>
<!ATTLIST fechadeconstitucion ano CDATA #REQUIRED>
<!ELEMENT categoria (#PCDATA)>
<!ATTLIST categoria categoriaFutbol %categoriaFutbol; "Primera_Division" >
<!ELEMENT entrenador_equi (#PCDATA)>
<!ATTLIST entrenador_equi id_entrenador IDREF #REQUIRED>
<!ELEMENT jugadores_equi (jugador_equi+)>
<!ELEMENT jugador_equi (#PCDATA)>
<!ATTLIST jugador_equi id_jugador IDREF #REQUIRED>
<!ELEMENT estadio_equi (#PCDATA)>
<!ATTLIST estadio_equi id_estadio IDREF #REQUIRED>

<!-- PARTIDOS -->
<!ELEMENT partidos (partido+)>
<!ELEMENT partido (equipos_par+,estadio_par, arbitro_par)>
<!ATTLIST partido id_partido ID #REQUIRED>
<!ELEMENT equipos_par (equipo_par+)>
<!ELEMENT equipo_par (#PCDATA)>
<!ATTLIST equipo_par id_equipo IDREF #REQUIRED>
<!ELEMENT estadio_par (#PCDATA)>
<!ATTLIST estadio_par id_estadio IDREF #REQUIRED>
<!ELEMENT arbitro_par (#PCDATA)>
<!ATTLIST arbitro_par id_arbitro IDREF #REQUIRED>

<!-- JORNADAS -->
<!ELEMENT jornadas (jornada+)>
<!ELEMENT jornada (fechadejornada+,competicion,partidos_jor+,emision+,canales+)>
<!ATTLIST jornada id_jornada ID #REQUIRED>
<!ELEMENT fechadejornada EMPTY>
<!ATTLIST fechadejornada dia %dia; #REQUIRED>
<!ATTLIST fechadejornada mes %mes; #REQUIRED>
<!ATTLIST fechadejornada ano CDATA #REQUIRED>
<!ELEMENT competicion (#PCDATA)>
<!ATTLIST competicion nombre CDATA "Liga Espa単ola 2021/2022">
<!ELEMENT partidos_jor (partido_jor+)>
<!ELEMENT partido_jor (#PCDATA)>
<!ATTLIST partido_jor id_partido IDREF #REQUIRED>
<!ELEMENT emision EMPTY>
<!ATTLIST emision nombre %emision; #REQUIRED>
<!ELEMENT canales (#PCDATA)>

=== Caberbar/1DAW-ML/2º Trimestre/liga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligas SYSTEM "./liga.dtd">

<ligas>
    <liga temporada="2011/2012" categoriaFutbol="Primera_Division">
        <jugadores>
            <jugador id_jugador="JUG_77969117Z">
                <nombre>Cristiano </nombre>
                <apellidos>Ronaldo</apellidos>
                <fechanacimiento dia="05" mes="Febrero" ano="1985" />
                <alias>CR7</alias>
                <alias>El bicho</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Delantero" />
            </jugador>
            <jugador id_jugador="JUG_35338804V">
                <nombre>Lionel Andrés Messi</nombre>
                <apellidos>Cuccittini</apellidos>
                <fechanacimiento dia="24" mes="Junio" ano="1987" />
                <alias>La pulga</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Delantero" />
            </jugador>
            <jugador id_jugador="JUG_29694820A">
                <nombre>Neymar</nombre>
                <apellidos>da Silva Santor Júnior</apellidos>
                <fechanacimiento dia="05" mes="Febrero" ano="1992" />
                <alias>Ney</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Delantero" />
            </jugador>
            <jugador id_jugador="JUG_54721582M">
                <nombre>Eden</nombre>
                <apellidos>Hazard</apellidos>
                <fechanacimiento dia="07" mes="Enero" ano="1991" />
                <alias>El duque</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Delantero" />
            </jugador>
            <jugador id_jugador="JUG_36596186N">
                <nombre>Kevin</nombre>
                <apellidos>De Bruyne</apellidos>
                <fechanacimiento dia="28" mes="Junio" ano="1991" />
                <alias>The Prince</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Centro" />
            </jugador>
            <jugador id_jugador="JUG_90585572A">
                <nombre>Robert</nombre>
                <apellidos>Lewandowski</apellidos>
                <fechanacimiento dia="21" mes="Agosto" ano="1988" />
                <alias>Lewy</alias>
                <alias>Mr. Lewangoalski</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Delantero" />
            </jugador>
            <jugador id_jugador="JUG_93938518D">
                <nombre>Antoine</nombre>
                <apellidos>Griezmann</apellidos>
                <fechanacimiento dia="21" mes="Marzo" ano="1991" />
                <alias>Principito</alias>
                <alias>Grizi</alias>
                <alias>Grizou</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Delantero" />
            </jugador>
            <jugador id_jugador="JUG_47238818S">
                <nombre>Sergio</nombre>
                <apellidos>Ramos García</apellidos>
                <fechanacimiento dia="30" mes="Marzo" ano="1986" />
                <alias>Sergi</alias>
                <nacionalidad lugar="Española" />
                <demarcacion posicion="Defensa" />
            </jugador>
            <jugador id_jugador="JUG_02985953R">
                <nombre>Paulo</nombre>
                <apellidos>Exequiel Dybala</apellidos>
                <fechanacimiento dia="15" mes="Noviembre" ano="1993" />
                <alias>La joya</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Delantero" />
            </jugador>
            <jugador id_jugador="JUG_34462353G">
                <nombre>Jan</nombre>
                <apellidos>Oblak</apellidos>
                <fechanacimiento dia="07" mes="Enero" ano="1993" />
                <alias>San Oblak</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Portero" />
            </jugador>
            <jugador id_jugador="JUG_49861543G">
                <nombre>Hugo Hadrien</nombre>
                <apellidos>Dominique Loris</apellidos>
                <fechanacimiento dia="26" mes="Diciembre" ano="1986" />
                <alias>Lloris</alias>
                <nacionalidad lugar="Extranjera" />
                <demarcacion posicion="Portero" />
            </jugador>
            <jugador id_jugador="JUG_35289935T">
                <nombre>Pablo</nombre>
                <apellidos>Martín Páez Gavira</apellidos>
                <fechanacimiento dia="05" mes="Agosto" ano="2004" />
                <alias>Gavi</alias>
                <nacionalidad lugar="Española" />
                <demarcacion posicion="Centro" />
            </jugador>
        </jugadores>
        <entrenadores>
            <entrenador id_entrenador="ENT_93279854L">
                <nombre>Josep</nombre>
                <apellidos>Guardiola i Sala</apellidos>
                <fechanacimiento dia="18" mes="Enero" ano="1971" />
                <alias>El filósofo</alias>
                <alias>pep</alias>
                <alias>El Noi de Santpedor</alias>
                <nacionalidad lugar="Española" />
                <titulos>32</titulos>
            </entrenador>
            <entrenador id_entrenador="ENT_41456142E">
                <nombre>Zinédine </nombre>
                <apellidos>Yazid Zidane</apellidos>
                <fechanacimiento dia="23" mes="Junio" ano="1972" />
                <alias>Zizou</alias>
                <nacionalidad lugar="Extranjera" />
                <titulos>11</titulos>
            </entrenador>
            <entrenador id_entrenador="ENT_31392049Q">
                <nombre>José Mário</nombre>
                <apellidos>Benítez Maudes</apellidos>
                <fechanacimiento dia="16" mes="Abril" ano="1960" />
                <alias>The Special One</alias>
                <nacionalidad lugar="Extranjera" />
                <titulos>25</titulos>
            </entrenador>
            <entrenador id_entrenador="ENT_78360882C">
                <nombre>Rafael </nombre>
                <apellidos>Martín Páez Gavira</apellidos>
                <fechanacimiento dia="05" mes="Agosto" ano="2004" />
                <alias>Rafa</alias>
                <nacionalidad lugar="Española" />
                <titulos>15</titulos>
            </entrenador>
        </entrenadores>
        <arbitros>
            <arbitro id_arbitro="ARB_98636272J">
                <nombre>Pierluigi</nombre>
                <apellidos>Collina</apellidos>
                <alias>Pierluigi</alias>
                <nacionalidad lugar="Extranjera"/>
            </arbitro>
            <arbitro id_arbitro="ARB_65364814X">
                <nombre>Markus</nombre>
                <apellidos>Merk</apellidos>
                <alias>Markus</alias>
                <nacionalidad lugar="Extranjera"/>
            </arbitro>
            <arbitro id_arbitro="ARB_54483285B">
                <nombre>Jesús</nombre>
                <apellidos>Gil Manzano</apellidos>
                <alias>Jesús</alias>
                <nacionalidad lugar="Española"/>
            </arbitro>
            <arbitro id_arbitro="ARB_40020115T">
                <nombre>Horacio</nombre>
                <apellidos>Marcelo Elizondo</apellidos>
                <alias>Chino</alias>
                <nacionalidad lugar="Extranjera"/>
            </arbitro>
        </arbitros>
        <estadios>
            <estadio id_estadio="EST_785">
                <nombre>Santiago Bernabéu</nombre>
                <ubicacion>España</ubicacion>
                <aforo>81 044</aforo>
            </estadio>
            <estadio id_estadio="EST_784">
                <nombre>Old Trafford</nombre>
                <ubicacion>Reino Unido</ubicacion>
                <aforo>76 000</aforo>
            </estadio>
            <estadio id_estadio="EST_934">
                <nombre>Spotify Camp Nou</nombre>
                <ubicacion>España</ubicacion>
                <aforo>99 354</aforo>
            </estadio>
            <estadio id_estadio="EST_145">
                <nombre>Allianz Arena</nombre>
                <ubicacion>Alemania</ubicacion>
                <aforo>75 024</aforo>
            </estadio>
        </estadios>
        <equipos>
            <equipo id_equipo="EQUI_147">
                <nombre>Real Madrid Club de Fútbol</nombre>
                <fechadeconstitucion dia="06" mes="Marzo" ano="1902" />
                <categoria categoriaFutbol="Primera_Division"/>
                <entrenador_equi id_entrenador="ENT_93279854L"/>
                <jugadores_equi>
                    <jugador_equi id_jugador="JUG_77969117Z"/>
                    <jugador_equi id_jugador="JUG_35338804V"/>
                    <jugador_equi id_jugador="JUG_29694820A"/>
                </jugadores_equi>
                <estadio_equi id_estadio="EST_785"/>
            </equipo>
            <equipo id_equipo="EQUI_185">
                <nombre>Manchester United Football Club</nombre>
                <fechadeconstitucion dia="05" mes="Marzo" ano="1878" />
                <categoria categoriaFutbol="Primera_Division"/>
                <entrenador_equi id_entrenador="ENT_41456142E"/>
                <jugadores_equi>
                    <jugador_equi id_jugador="JUG_54721582M"/>
                    <jugador_equi id_jugador="JUG_36596186N"/>
                    <jugador_equi id_jugador="JUG_90585572A"/>
                </jugadores_equi>
                <estadio_equi id_estadio="EST_784"/>
            </equipo>
            <equipo id_equipo="EQUI_263">
                <nombre>Fußball-Club Bayern München e. V.</nombre>
                <fechadeconstitucion dia="27" mes="Febrero" ano="1900" />
                <categoria categoriaFutbol="Primera_Division"/>
                <entrenador_equi id_entrenador="ENT_31392049Q"/>
