=== Caberbar/1DAW-ML/2º Trimestre/XSD/ligaFutbol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ligas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="liga">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jugadores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="jugador" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="entrenadores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="entrenador" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="arbitros">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="arbitro" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="estadios">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="estadio" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="equipos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="equipo" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="partidos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="partido" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="jornadas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="jornada" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="temporada" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="2011_2012" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="categoria" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="PrimeraDivision"/>
                                    <xs:enumeration value="SegundaDivision" />
                                    <xs:enumeration value="TerceraDivision" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DE JUGADOR -->
    <xs:element name="jugador">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="alias" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="fechaNacimiento" type="tFecha"/>
                <xs:element ref="nacionalidad" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="identificador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="JUG_[0-9]{8}[A-Z]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="demarcacion" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Portero" />
                        <xs:enumeration value="Defensa" />
                        <xs:enumeration value="Delantero" />
                        <xs:enumeration value="Centro" />
                        <xs:enumeration value="Lateral" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DE ENTRENADOR -->    
    <xs:element name="entrenador">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="alias" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="fechaNacimiento" type="tFecha"/>
                <xs:element ref="nacionalidad" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="identificador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="ENT_[0-9]{8}[A-Z]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="titulos" type="xs:integer" use="optional" />
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DE ARBITRO -->   
    <xs:element name="arbitro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="alias" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                <xs:element ref="nacionalidad" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="identificador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="ARB_[0-9]{8}[A-Z]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DE ESTADRIO -->       
    <xs:element name="estadio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="2"/>
            </xs:sequence>
            <xs:attribute name="identificador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="EST_[0-9]{3}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="ubicacion" type="xs:string" use="required" />
            <xs:attribute name="aforo" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DE EQUIPO -->       
    <xs:element name="equipo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="2"/>
                <xs:element name="fechaConstitucion" type="tFecha"/>
                <xs:element name="jugadoresID">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jugadorID" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="identificador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="EQU_[0-9]{3}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="categoria">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="PrimeraDivision" />
                        <xs:enumeration value="SegundaDivision" />
                        <xs:enumeration value="TerceraDivision" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="entrenador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ENT_[0-9]{8}[A-Z]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="estadio" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="EST_[0-9]{3}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DE PARTIDO -->       
    <xs:element name="partido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equiposID">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipoID" minOccurs="1" maxOccurs="2">
                                <xs:complexType>
                                    <xs:attribute name="identificador">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="EQU_[0-9]{3}" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="identificador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="PAR_[0-9]{3}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="estadio" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="EST_[0-9]{3}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="arbitro" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ARB_[0-9]{8}[A-Z]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DE JORNADA -->       
    <xs:element name="jornada">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fecha" type="tFecha"/>
                <xs:element name="partidosJornada">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partidoID" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="identificador" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="PAR_[0-9]{3}" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="hora" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="0"/>
                                                <xs:maxInclusive value="23"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="canales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="canal" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="identificador" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="JOR_[0-9]{3}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="competicion" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="2021_2022" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="emision" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Codificado" />
                        <xs:enumeration value="Abierto" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- DECLARACION DEL ELEMENTO FECHA -->       
    <xs:complexType name="tFecha">
        <xs:attribute name="anno">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{4}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="mes">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="Enero"/>
                    <xs:enumeration value="Febrero"/>
                    <xs:enumeration value="Marzo"/>
                    <xs:enumeration value="Abril"/>
                    <xs:enumeration value="Mayo"/>
                    <xs:enumeration value="Junio"/>
                    <xs:enumeration value="Julio"/>
                    <xs:enumeration value="Agosto"/>
                    <xs:enumeration value="Septiembre"/>
                    <xs:enumeration value="Octubre"/>
                    <xs:enumeration value="Noviembre"/>
                    <xs:enumeration value="Diciembre"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="dia">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                        <xs:enumeration value="1"/>
                        <xs:enumeration value="2"/>
                        <xs:enumeration value="3"/>
                        <xs:enumeration value="4"/>
                        <xs:enumeration value="5"/>
                        <xs:enumeration value="6"/>
                        <xs:enumeration value="7"/>
                        <xs:enumeration value="8"/>
                        <xs:enumeration value="9"/>
                        <xs:enumeration value="10"/>
                        <xs:enumeration value="11"/>
                        <xs:enumeration value="12"/>
                        <xs:enumeration value="13"/>
                        <xs:enumeration value="14"/>
                        <xs:enumeration value="15"/>
                        <xs:enumeration value="16"/>
                        <xs:enumeration value="17"/>
                        <xs:enumeration value="18"/>
                        <xs:enumeration value="19"/>
                        <xs:enumeration value="20"/>
                        <xs:enumeration value="21"/>
                        <xs:enumeration value="22"/>
                        <xs:enumeration value="23"/>
                        <xs:enumeration value="24"/>
                        <xs:enumeration value="25"/>
                        <xs:enumeration value="26"/>
                        <xs:enumeration value="27"/>
                        <xs:enumeration value="28"/>
                        <xs:enumeration value="29"/>
                        <xs:enumeration value="30"/>
                        <xs:enumeration value="31"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- DECLARACION DEL ELEMENTO NACIONALIDAD -->       
    <xs:element name="nacionalidad">
        <xs:complexType>
            <xs:attribute name="tipo" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="Espanola" />
                        <xs:enumeration value="Extranjera" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Caberbar/1DAW-ML/2º Trimestre/XSD/ligaFutbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<ligas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ligaFutbol.xsd">
    <liga temporada="2011_2012" categoria="SegundaDivision">
        <jugadores>
            <jugador identificador="JUG_11111111P" demarcacion="Delantero">
                <nombre>Lionel</nombre>
                <apellido>Andrés</apellido>
                <apellido>Messi</apellido>
                <alias>La Pulga</alias>
                <fechaNacimiento dia="24" mes="Junio" anno="1987"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_22222222P" demarcacion="Delantero">
                <nombre>Cristiano Ronaldo</nombre>
                <apellido>dos Santos</apellido>
                <apellido>Aveiro</apellido>
                <alias>CR7</alias>
                <fechaNacimiento dia="5" mes="Febrero" anno="1985"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_33333333P" demarcacion="Delantero">
                <nombre>Neymar da Silva</nombre>
                <apellido>Santos</apellido>
                <apellido>Júnior</apellido>
                <alias>Neymar</alias>
                <fechaNacimiento dia="1" mes="Enero" anno="1997"/>
            </jugador>
            <jugador identificador="JUG_44444444P" demarcacion="Delantero">
                <nombre>Kylian</nombre>
                <apellido>Mbappé</apellido>
                <apellido>Lottin</apellido>
                <alias>Donatello</alias>
                <fechaNacimiento dia="5" mes="Enero" anno="1985"/>
            </jugador>
            <jugador identificador="JUG_55555555P" demarcacion="Portero">
                <nombre>Kevin</nombre>
                <apellido>De Bruyne</apellido>
                <alias>The Prince</alias>
                <fechaNacimiento dia="28" mes="Julio" anno="1991"/>
            </jugador>
            <jugador identificador="JUG_66666666P" demarcacion="Delantero">
                <nombre>Sergio</nombre>
                <apellido>Ramos</apellido>
                <apellido>García</apellido>
                <alias>Ramin</alias>
                <fechaNacimiento dia="30" mes="Mayo" anno="1986"/>
            </jugador>
            <jugador identificador="JUG_77777777P" demarcacion="Defensa">
                <nombre>Virgil </nombre>
                <apellido>van Dijk</apellido>
                <alias>Dijk</alias>
                <fechaNacimiento dia="8" mes="Julio" anno="1991"/>
            </jugador>
            <jugador identificador="JUG_88888888P" demarcacion="Delantero">
                <nombre>Robert</nombre>
                <apellido>Lewandowski</apellido>
                <alias>Lewandowski</alias>
                <fechaNacimiento dia="21" mes="Julio" anno="1988"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_99999999P" demarcacion="Centro">
                <nombre>Luka</nombre>
                <apellido>Modrić</apellido>
                <alias>Modrić</alias>
                <fechaNacimiento dia="9" mes="Septiembre" anno="1985"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_10101010P" demarcacion="Centro">
                <nombre>Sergio</nombre>
                <apellido>Leonel</apellido>
                <apellido>Agüero</apellido>
                <alias>Agüero</alias>
                <fechaNacimiento dia="2" mes="Julio" anno="1985"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_20202020P" demarcacion="Portero">
                <nombre>Jan</nombre>
                <apellido>Oblak</apellido>
                <alias>Jan</alias>
                <fechaNacimiento dia="7" mes="Junio" anno="1993"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_30303030P" demarcacion="Defensa">
                <nombre>Kalidou</nombre>
                <apellido>Koulibaly</apellido>
                <alias>Koulibaly</alias>
                <fechaNacimiento dia="20" mes="Junio" anno="1991"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_40404040P" demarcacion="Centro">
                <nombre>Sergio</nombre>
                <apellido>Busquets</apellido>
                <apellido>Burgos</apellido>
                <alias>Busquets</alias>
                <fechaNacimiento dia="16" mes="Julio" anno="1991"/>
                <nacionalidad tipo="Espanola"/>
            </jugador>
            <jugador identificador="JUG_50505050P" demarcacion="Centro">
                <nombre>Bernardo</nombre>
                <apellido>Silva</apellido>
                <alias>El Pistolero</alias>
                <fechaNacimiento dia="10" mes="Agosto" anno="1995"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_60606060P" demarcacion="Delantero">
                <nombre>Paulo Bruno</nombre>
                <apellido>Exequiel</apellido>
                <apellido>Dybala</apellido>
                <alias>La joya</alias>
                <fechaNacimiento dia="15" mes="Noviembre" anno="1993"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_70707070P" demarcacion="Delantero">
                <nombre>Raheem</nombre>
                <apellido>Shaquilla</apellido>
                <apellido>Sterling</apellido>
                <alias>Shaquilla</alias>
                <fechaNacimiento dia="8" mes="Diciembre" anno="1998"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_80808080P" demarcacion="Delantero">
                <nombre>Sergio</nombre>
                <apellido>Reguilón</apellido>
                <apellido>Castillo</apellido>
                <alias>Reguilón</alias>
                <fechaNacimiento dia="5" mes="Diciembre" anno="1996"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_90909090P" demarcacion="Centro">
                <nombre>Houssem</nombre>
                <apellido>Aouar</apellido>
                <alias>Aouar</alias>
                <fechaNacimiento dia="30" mes="Julio" anno="1998"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_91919191P" demarcacion="Centro">
                <nombre>Jadon</nombre>
                <apellido>Malik</apellido>
                <apellido>Sancho</apellido>
                <alias>Jadon Malik</alias>
                <fechaNacimiento dia="20" mes="Marzo" anno="2000"/>
                <nacionalidad tipo="Extranjera"/>
            </jugador>
            <jugador identificador="JUG_92929292P" demarcacion="Defensa">
                <nombre>Jose</nombre>
                <apellido>Rodrigez</apellido>
                <alias>Pepe</alias>
                <fechaNacimiento dia="27" mes="Marzo" anno="1995"/>
                <nacionalidad tipo="Espanola"/>
            </jugador>
        </jugadores>

        <entrenadores>
            <entrenador identificador="ENT_11111111P" titulos="4">
                <nombre>Diego</nombre>
                <apellido>Simeone</apellido>
                <alias>Cholo</alias>
                <fechaNacimiento dia="28" mes="Abril" anno="1970"/>
                <nacionalidad tipo="Extranjera"/>
            </entrenador>
            <entrenador identificador="ENT_22222222P" titulos="7">
                <nombre>Pep</nombre>
                <apellido>Guardiola</apellido>
                <alias>Guardiola</alias>
                <fechaNacimiento dia="18" mes="Junio" anno="1971"/>
                <nacionalidad tipo="Espanola" />
            </entrenador>
            <entrenador identificador="ENT_33333333P" titulos="10">
                <nombre>Julen</nombre>
                <apellido>Lopetegui</apellido>
                <alias>Lopetegui</alias>
                <fechaNacimiento dia="28" mes="Agosto" anno="1966"/>
                <nacionalidad tipo="Espanola" />
            </entrenador>
            <entrenador identificador="ENT_44444444P" titulos="10">
                <nombre>Quite</nombre>
                <apellido>Setién</apellido>
                <alias>Lopetegui</alias>
                <fechaNacimiento dia="9" mes="Septiembre" anno="1958"/>
            </entrenador>
        </entrenadores>

        <arbitros>
            <arbitro identificador="ARB_11111111P">
                <nombre>Alberto</nombre>
                <apellido>Undiano</apellido>
                <apellido>Mallenco</apellido>
                <alias>El Niño de Oro</alias>
            </arbitro>
            <arbitro identificador="ARB_22222222P">
                <nombre>David</nombre>
                <apellido>Fernandez</apellido>
                <apellido>Borbalan</apellido>
                <alias>El Chiquitín</alias>
            </arbitro>
        </arbitros>

        <estadios>
            <estadio identificador="EST_111" ubicacion="Madrid" aforo="81044">
                <nombre>Santiago Bernabéu</nombre>
            </estadio>
            <estadio identificador="EST_222" ubicacion="Barcelona" aforo="99354">
                <nombre>Camp Nou</nombre>
            </estadio>
            <estadio identificador="EST_333" ubicacion="Madrid" aforo="68000">
                <nombre>Wanda Metropolitano</nombre>
            </estadio>
            <estadio identificador="EST_444" ubicacion="Valencia" aforo="55000">
                <nombre>Mestalla</nombre>
            </estadio>
        </estadios>

        <equipos>
            <equipo identificador="EQU_111" categoria="PrimeraDivision" entrenador="ENT_11111111P" estadio="EST_111">
