=== Caberbar/1DAW-ML/2º Trimestre/XSD/persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema">
    <xsi:element name="persona">
        <xsi:complexType>
            <xsi:sequence>
                <xsi:element name="nombre" type="xsi:string"/>
                <xsi:element name="mujer" type="xsi:string"/>
                <xsi:element name="fecha-de-nacimiento"/>
                    <xsi:complexType>
                        <xsi:sequence>
                            <xsi:element name="dia" type="xsi:string"/>
                            <xsi:element name="mes" type="xsi:string"/>
                            <xsi:element name="anyo" type="xsi:string"/>
                        </xsi:sequence>
                    </xsi:complexType>
                </xsi:element>
                <xsi:element name="ciudad" type="xsi:string"/>
            </xsi:sequence>
        </xsi:complexType>
    </xsi:element>
</xsi:schema>

=== Caberbar/1DAW-ML/2º Trimestre/XSD/ej2.xml
<?xml version="1.0" encoding="UTF-8"?>

<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="persona.xsd">
    <nombre>Elsa</nombre>
    <mujer/>
    <fecha-de-nacimiento>
        <dia>18</dia>
        <mes>6</mes>
        <anyo>1996</anyo>
    </fecha-de-nacimiento>
    <ciudad>Pamplona</ciudad>
</persona>
