=== Caberbar/1DAW-ML/2º Trimestre/XSD/prueba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Cliente" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IdCliente" type="xs:integer"></xs:element>
                            <xs:element name="Empresa" type="xs:string"></xs:element>
                            <xs:element name="Contacto" type="xs:string"></xs:element>
                            <xs:element name="Ciudad" type="xs:string"></xs:element>
                            <xs:element name="Provincia" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

<!--            ASIGNATURA                                                                              -->
                
                <xs:element name="asignatura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nombre"/>
                            <xs:element name="creditos_teoricos" type="decimales" />
                            <xs:element name="creditos_practicos" type="decimales" />
                            <xs:element name="trimestre" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute ref="id"/>
                        <xs:attribute ref="titulacion"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="carrera" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre_carrera" type="xs:string" />
                            <xs:element ref="plan"/>
                            <xs:element name="creditos" type="xs:integer"/>
                            <xs:element ref="centro"/>
                            <xs:element name="subdirector" type="xs:string" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute ref="idCarrera"/>
                    </xs:complexType>
                </xs:element>
<!--            CARRERA                                                                              -->
            
                <xs:element name="alumno">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="apellido1" type="xs:string"/>
                            <xs:element name="apellido2" type="xs:string"/>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element ref="sexo"/>
                            <xs:element ref="estudios"/>
                        </xs:sequence>
                        <xs:attribute ref="idAlumno"/>
                        <xs:attribute ref="beca"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="nombre">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="120"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:attribute name="id">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="a[0-9]{2}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="titulacion">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="c[0-9]{2}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:simpleType name="decimales">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"></xs:minInclusive>
            <xs:maxInclusive value="99"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

<!--            CARRERA                                                                              -->

    <xs:element name="plan">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:pattern value="[0-9]{4}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="centro">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:enumeration value="Escuela de Informatica"/>
                <xs:enumeration value="Facultad de Ciencias Sociales"/>
                <xs:enumeration value="Facultad de Ciencias Experimentales"/>
                <xs:enumeration value="Facultad de Humanidades"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:attribute name="idCarrera">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="c[0-9]{2}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="sexo">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:enumeration value="Hombre"/>
                <xs:enumeration value="Mujer"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="estudios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="carrera">
                    <xs:complexType>
                        <xs:sequence></xs:sequence>
                        <xs:attribute name="codigo">
                            <xs:simpleType>
                                <xs:restriction base="xs:IDREF">
                                    <xs:pattern value="c[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="asignaturas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="asignatura" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence></xs:sequence>
                                    <xs:attribute name="codigo">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:IDREF">
                                                <xs:pattern value="a[0-9]{2}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="proyecto" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="idAlumno">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="e[0-9]{2}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="beca">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:enumeration value="si"/>
                <xs:enumeration value="no"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

</xs:schema>

=== Caberbar/1DAW-ML/2º Trimestre/XSD/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="prueba.xsd">
    <Cliente>
        <IdCliente>1</IdCliente>
        <Empresa>Defensa Personal Orient</Empresa>
        <Contacto>Alfonso Papo</Contacto>
        <Ciudad>Terrassa</Ciudad>
        <Provincia>Barcelona</Provincia>
    </Cliente>
    <Cliente>
        <IdCliente>2</IdCliente>
        <Empresa>Mística y Salud S.A.</Empresa>
        <Contacto>Ana Coreta</Contacto>
        <Ciudad>Santander</Ciudad>
        <Provincia>Santander</Provincia>
    </Cliente>
    <Cliente>
        <IdCliente>3</IdCliente>
        <Empresa>Paños Rias Bajas</Empresa>
        <Contacto>Estela Marinera</Contacto>
        <Ciudad>Vigo</Ciudad>
        <Provincia>Pontevedra</Provincia>
    </Cliente>

    <asignatura id="a06" titulacion="c03">
        <nombre>Didactica</nombre>
        <creditos_teoricos>4</creditos_teoricos>
        <creditos_practicos>3</creditos_practicos>
        <trimestre>2</trimestre>
    </asignatura>

    <carrera idCarrera="c02">
        <nombre_carrera>Dipl. Empresariales</nombre_carrera>
        <plan>2001</plan>
        <creditos>275</creditos>
        <centro>Facultad de Ciencias Sociales</centro>
    </carrera>

    <carrera idCarrera="c03">
        <nombre_carrera>Dipl. Relaciones Laborales</nombre_carrera>
        <plan>2001</plan>
        <creditos>280</creditos>
        <centro>Facultad de Ciencias Sociales</centro>
        <subdirector>Alfonso Martin Luque</subdirector>
    </carrera>

    <alumno idAlumno="e09" beca="si">
        <apellido1>Rodriguez</apellido1>
        <apellido2>Perez</apellido2>
        <nombre>Mauricio Jesus</nombre>
        <sexo>Hombre</sexo>
        <estudios>
            <carrera codigo="c03"/>
            <asignaturas>
                <asignatura codigo="a06"/>
                <asignatura codigo="a06"/>
                <asignatura codigo="a06"/>
                <asignatura codigo="a06"/>
            </asignaturas>
            <proyecto>El Tejido Empresarial</proyecto>
        </estudios>
    </alumno>
 
</Clientes>
